workspace = { members = ["ex_2/ex_2"] }
[package]
name = "ltc_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
